PhonebookUIApp/Models/UserData.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PhonebookUIApp.Models
{
    public class UserData
    {
        public int UserId { get; set; }

        public string UserName { get; set; }
    }
}

PhonebookUIApp/Models/UserModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PhonebookUIApp.Models
{
    public class UserModel
    {
        public List<UserData> Users { get; set; }

        public List<UserPhoneBookData> PhoneBook { get; set; }

        public UserData NewUser { get; set; }

        public UserPhoneBook NewPhonebookRecord { get; set; }

        public UserModel()
        {
            Users = new List<UserData>();
            PhoneBook = new List<UserPhoneBookData>();
        }
    }

    public class UserPhoneBookData
    {
        public UserData User { get; set; }

        public List<UserData> Contacts { get; set; }
    } 
}

PhonebookUIApp/Models/UserPhoneBook.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PhonebookUIApp.Models
{
    public class UserPhoneBook
    {
        public int RecordId { get; set; }
        public int UserId { get; set; }
        public int ContactId { get; set; }
    }
}

PhonebookUIApp/Controllers/HomeController.cs
using DataAccessLayer;
using PhonebookUIApp.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PhonebookUIApp.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            //SQL Server
            SQLDALManager manager = new SQLDALManager("dbConnKey");
            DataTable allUsers = manager.ExecuteStoredProcedure("getAllUsers");

            List<UserData> usersList = new List<UserData>();
            List<UserPhoneBookData> phonebook = new List<UserPhoneBookData>();
            foreach (DataRow dr in allUsers.Rows)
            {
                UserData user = new UserData
                {
                    UserId = Convert.ToInt32(dr["user_id"]),
                    UserName = dr["user_name"].ToString()
                };
                usersList.Add(user);

                List<SqlParameter> param = new List<SqlParameter>();
                param.Add(new SqlParameter("@userId", Convert.ToInt32(dr["user_id"])));
                DataTable contacts = manager.ExecuteStoredProcedure("getContacts", param);

                List<UserData> contcts = new List<UserData>();
                foreach (DataRow contact in contacts.Rows)
                {
                    contcts.Add(new UserData
                    {
                        UserId = Convert.ToInt32(contact["user_id"]),
                        UserName = contact["user_name"].ToString()
                    });
                }
                phonebook.Add(new UserPhoneBookData { User = user, Contacts = contcts });
            }
            



            //Dummy data
            //List<UserData> dummyUsers = new List<UserData>
            //{
            //    new UserData { UserId = 1, UserName = "Alice"},
            //    new UserData { UserId = 2, UserName = "Bob"},
            //    new UserData { UserId = 3 , UserName = "Micheal"}
            //};

            //List<UserPhoneBookData> dummyPhonebook = new List<UserPhoneBookData>
            //{
            //    new UserPhoneBookData { User = usersList[0],
            //        Contacts = new List<UserData>{ usersList[1], usersList[2] } }
            //};

            UserModel model = new UserModel
            {
                Users = usersList,
                PhoneBook = phonebook
            };

            // strongly typed view concept
            return View(model);
        }
    }
}

PhonebookUIApp/Controllers/PhoneBookController.cs
using DataAccessLayer;
using PhonebookUIApp.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PhonebookUIApp.Controllers
{
    public class PhoneBookController : Controller
    {
        // GET: PhoneBook
        public ActionResult Index()
        {
            //SQL Server
            SQLDALManager manager = new SQLDALManager("dbConnKey");
            DataTable allUsers = manager.ExecuteStoredProcedure("getAllUsers");

            List<UserData> usersList = new List<UserData>();
            List<UserPhoneBookData> phonebook = new List<UserPhoneBookData>();
            foreach (DataRow dr in allUsers.Rows)
            {
                UserData user = new UserData
                {
                    UserId = Convert.ToInt32(dr["user_id"]),
                    UserName = dr["user_name"].ToString()
                };
                usersList.Add(user);

                List<SqlParameter> param = new List<SqlParameter>();
                param.Add(new SqlParameter("@userId", Convert.ToInt32(dr["user_id"])));
                DataTable contacts = manager.ExecuteStoredProcedure("getContacts", param);

                List<UserData> contcts = new List<UserData>();
                foreach (DataRow contact in contacts.Rows)
                {
                    contcts.Add(new UserData
                    {
                        UserId = Convert.ToInt32(contact["user_id"]),
                        UserName = contact["user_name"].ToString()
                    });
                }
                phonebook.Add(new UserPhoneBookData { User = user, Contacts = contcts });
            }

            //Dummy data
            //List<UserData> dummyUsers = new List<UserData>
            //{
            //    new UserData { UserId = 1, UserName = "Alice"},
            //    new UserData { UserId = 2, UserName = "Bob"},
            //    new UserData { UserId = 3 , UserName = "Micheal"}
            //};

            //List<UserPhoneBookData> dummyPhonebook = new List<UserPhoneBookData>
            //{
            //    new UserPhoneBookData { User = usersList[0],
            //        Contacts = new List<UserData>{ usersList[1], usersList[2] } }
            //};

            UserModel model = new UserModel
            {
                Users = usersList,
                PhoneBook = phonebook
            };

            // strongly typed view concept
            return View(model);
        }

        [HttpPost]
        public ActionResult Create(UserModel data)
        {
            SQLDALManager manager = new SQLDALManager("dbConnKey");
            manager.ExecuteStoredProcedure("createUserPhoneBook", new List<SqlParameter>
            {
                new SqlParameter("@userId",data.NewPhonebookRecord.UserId),
                new SqlParameter("@contactId",data.NewPhonebookRecord.ContactId)
            });
            return RedirectToAction("Index");
        }
    }
}

PhonebookUIApp/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

PhonebookUIApp/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

PhonebookUIApp/Views/Home/CreateUser.cshtml
@using PhonebookUIApp.Models
@model UserData

<h2>Create New User</h2>
@using (Html.BeginForm("Create", "Home", FormMethod.Post))
{
    @Html.LabelFor(m => m.UserName)
    @Html.TextBoxFor(m => m.UserName)
    <input type="submit" value="Submit" />
}

PhonebookUIApp/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Phonebook";
}

@using PhonebookUIApp.Models
@model UserModel

<div class="main">
    <div class="users">
        <p>Users List:</p>
        <ul class="userslist">
            @foreach (UserData user in Model.Users)
            {
                <li>UserID: @user.UserId, UserName: @user.UserName</li>
            }
        </ul>
    </div>

    <div class="actions">
        @Html.Partial("CreateUser", Model.NewUser)

        <h2>Update User</h2>

        <h2>Delete User</h2>
    </div>
</div>

PhonebookUIApp/Views/PhoneBook/Index.cshtml
@{
    ViewBag.Title = "Index";
}

@using PhonebookUIApp.Models
@model UserModel

<h2>PhoneBook Records</h2>

<div class="phonebook">
    <p>Phonebook:</p>
    @foreach (UserPhoneBookData phonebook in Model.PhoneBook)
    {
        if (phonebook.Contacts.Count > 0)
        {
            <ul class="phonebooklist">
                UserId:@phonebook.User.UserId, UserName: @phonebook.User.UserName
                @foreach (UserData contacts in phonebook.Contacts)
                {
                    <li>Contact Name: @contacts.UserName</li>
                }
            </ul>
        }
    }
</div>

<div class="actions">
    <h4>Create new phonebook Record</h4>
    @using (Html.BeginForm("Create", "PhoneBook", FormMethod.Post))
    {
        @Html.LabelFor(m=>m.NewPhonebookRecord.UserId)
        @Html.TextAreaFor(m=>m.NewPhonebookRecord.UserId)

        @Html.LabelFor(m=>m.NewPhonebookRecord.ContactId)
        @Html.TextAreaFor(m=>m.NewPhonebookRecord.ContactId)
        
        <input type="submit" value="Submit"/>
    }
</div>

PhonebookUIApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Phonebook", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Users", "Index", "Home")</li>
                    <li>@Html.ActionLink("Phonebook", "Index", "PhoneBook")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        @*<hr />*@
        @*<footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>*@
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>